version: "3.7"
services:
  database:
    image: postgres:latest
    ports:
      - "5444:5432"
    env_file:
      - .env
    volumes:
      - ./database/mad-fitness-init.sql:/docker-entrypoint-initdb.d/1-mad-fitness-init.sql
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - .env