version: "3.7"
services:
  database:
    image: postgres:latest
    ports:
      - "5444:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment: 
      DB_URL: postgres://postgres:password@database:5432/db
      ENTITY_PATH: dist/*/entity/*.entity{.js,.ts}